# Configuração de Conexão com o Banco do Professor
spring.datasource.url=jdbc:postgresql://comp-pga.qute.com.br:5432/u055
spring.datasource.username=u055
spring.datasource.password=faculdade12345678

# Fala pro Hibernate não tentar recriar as tabelas (porque já existem)
spring.jpa.hibernate.ddl-auto=none

# Mostra no console os comandos SQL que o Java tá rodando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect